language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - xvfb
cache:
  directories:
    - "node_modules"
before_install:
    - npm i -g tslint typescript codecov
script:
    - npm run lint
    - xvfb-run npm run test:ci
    - npm run build
after_success:
  - codecov