language: node_js
node_js:
  - "8"
  - "10"
addons:
  apt:
    packages:
      - xvfb
cache:
  directories:
    - "node_modules"
before_install:
    - npm i -g tslint typescript codecov
script:
    - npm run lint
    - xvfb-run npm run test:ci
    - npm run build
after_success:
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  fqdn: www.thepolishwedding.info
  on:
    branch: master