language: node_js
node_js:
  - "8"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN
  local_dir: dist
  fqdn: thepolishwedding.info
  on:
    branch: master
before_install:
    - npm i -g tslint typescript
cache:
  directories:
    - "node_modules"
script:
    - npm run lint
    - npm run build